backend:
  name: github
  repo: ToddLowell/ComeCommune
  branch: master

site_url: https://comecommune.netlify.app

publish_mode: editorial_workflow
media_folder: /static/assets
public_folder: /assets

collections:
  - name: articles
    label: 'Article Posts'
    label_singular: 'Article Post'
    description: >
      Articles published here will go under 'https://comecommune.netlify.app/articles/'.
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # name of file
    summary: '{{title}} -- {{day}}/{{month}}/{{year}}' # name of entry on admin page
    folder: articles
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: path, label: Slug, widget: string }
      - { name: date, label: Publish Date, widget: date, date_format: 'DD-MM--YYYY' }
      - { name: image, label: Cover Image, widget: image, allow_multiple: false, required: false }
      - { name: image_alt, label: 'Image Alt', widget: string, required: false }
      - { name: image_credit, label: 'Image Credit', widget: string, required: false }
      - { name: body, label: Body, widget: markdown }
